---

language: generic
os: linux
dist: xenial
sudo: required

addons:
  apt:
    sources:
      - docker-xenial
    packages:
    - docker

services:
- docker

script:
- sudo apt-get -qq -y update
- cd travis && ./travis-ci.sh
